run:
  timeout: 5m

linters:
  enable:
    - unused
    - govet
    - errcheck
    - staticcheck
    - gofmt
    - goimports
    - ineffassign
  disable:
    - deadcode
    - golint

issues:
  exclude-use-default: false
