run:
  timeout: 5m
  skip-dirs:
    - vendor
    - "pkg/mod"
    - "src"
  skip-files:
    - ".*_gen.go"
    - ".*.pb.go"

linters:
  enable:
    - govet
    - gofmt
    - errcheck
    - staticcheck
    - revive
    - unused

issues:
  exclude-use-default: false