version: "2"

run:
  tests: true

linters:
  enable:
    # Correctness / Bugs
    - errorlint
    - contextcheck
    - rowserrcheck
    - sqlclosecheck
    - bodyclose
    - predeclared
    - reassign
    - noctx
    - errname

    # Code Style / Readability
    - revive
    - nolintlint
    - godot
    - nakedret

    # Performance
    - prealloc

    # Unused / Clean Code
    - unconvert
    - unparam
    - thelper
    - tparallel
    - testableexamples

  settings:
    revive:
      severity: warning

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    gofmt:
      simplify: true
    goimports:
      local-prefixes:
        - weatherApi

# ❗ Виключення окремих шляхів і правил
exclude:
  - ^tests/architecture/             # Не лінтити архітектурні тести
  - ^third_party/
  - ^builtin/
  - ^examples/

linters-settings:
  exclude-rules:
    - path: _test\.go
      text: should not use dot imports
