run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly
  issues-exit-code: 1

linters:
  enable:
    - typecheck
    - gofmt
    - goimports
    - govet
    - ineffassign
    - misspell
    - revive
  disable:
    - errcheck # Can be noisy in tests

linters-settings:
  govet:
    check-shadowing: true
  revive:
    min-confidence: 0.8

issues:
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec