services:
  db:
    image: postgres:17.5
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - weather-api-pgdata:/var/lib/postgresql/data
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - '5432:5432'
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    
  redis:
    image: redis:7
    ports:
      - "6379:6379"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5

  api:
    build:
      context: .
      target: production
    env_file:
      - .env
    environment:
      - DB_URL=${DB_URL}
      - TEMPLATE_DIR=${TEMPLATE_DIR}
      - PGUSER=${PGUSER}
      - PGPASSWORD=${PGPASSWORD}
      - PGHOST=db
      - PGPORT=5432
      - REDIS_ADDR=redis:6379
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_DB=${REDIS_DB}
      - REDIS_POOL_SIZE=${REDIS_POOL_SIZE}
      - REDIS_TIMEOUT_SECONDS=${REDIS_TIMEOUT_SECONDS}
      - OPENWEATHER_API_KEY=${OPENWEATHER_API_KEY}
      - WEATHER_API_KEY=${WEATHER_API_KEY}
    ports:
      - "8080:8080"
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  test-runner-unit:
    build:
      context: .
      target: test
    env_file:
      - .env.test
    environment:
      - TEST_DB_URL=${TEST_DB_URL}
      - TEMPLATE_DIR=${TEMPLATE_DIR}
      - APP_BASE_URL=${APP_BASE_URL}
      - PGUSER=${PGUSER}
      - PGPASSWORD=${PGPASSWORD}
      - PGHOST=db
      - PGPORT=5432
      - REDIS_ADDR=redis:6379
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_DB=${REDIS_DB}
      - REDIS_POOL_SIZE=${REDIS_POOL_SIZE}
      - REDIS_TIMEOUT_SECONDS=${REDIS_TIMEOUT_SECONDS}
      - BUNDEBUG=1
    working_dir: /app
    command: ["/bin/bash", "-c", "make test-unit"]
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    profiles:
      - testing
  
  test-runner-integration:
    build:
      context: .
      target: test
    env_file:
      - .env.test
    environment:
      - TEST_DB_URL=${TEST_DB_URL}
      - TEMPLATE_DIR=${TEMPLATE_DIR}
      - APP_BASE_URL=${APP_BASE_URL}
      - PGUSER=${PGUSER}
      - PGPASSWORD=${PGPASSWORD}
      - PGHOST=db
      - PGPORT=5432
      - REDIS_ADDR=redis:6379
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_DB=${REDIS_DB}
      - REDIS_POOL_SIZE=${REDIS_POOL_SIZE}
      - REDIS_TIMEOUT_SECONDS=${REDIS_TIMEOUT_SECONDS}
      - BUNDEBUG=1
    working_dir: /app
    command: ["make", "test-integration"]
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    profiles:
      - testing

  test-runner-e2e:
    build:
      context: .
      dockerfile: tests/e2e/Dockerfile.playwright
    environment:
      - APP_BASE_URL=http://api:8080
    depends_on:
      api:
        condition: service_started
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    profiles:
      - testing

volumes:
  weather-api-pgdata: