version: '3.8'

services:
  db:
    image: postgres:17
    container_name: subscription_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: subscriptions
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  subscription-service:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "8080:8080"  # gRPC
      - "8081:8081"  # HTTP Gateway (Connect)
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: subscriptions
      MAILER_GRPC_ADDR: http://mailer:8080

  mailer:
    image: alpine:latest
    command: ["sh", "-c", "while true; do echo 'Stub mailer'; sleep 10; done"]
    ports:
      - "8082:8080"

volumes:
  db_data:
