services:
  weather-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: weather_service
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - OPENWEATHER_API_KEY=647bab43e62f0270d7c22658bd452cc0
      - WEATHER_API_KEY=ee532c4f8506474c8cc163802252106
      - ENVIRONMENT=dev
      - CACHE_ENABLED=true
      - REDIS_ADDR=weather-redis:6379
      - REDIS_PASSWORD=
      - REDIS_DB=0
      - REDIS_POOL_SIZE=10
      - REDIS_TIMEOUT_SECONDS=2
      - CACHE_EXPIRATION_MINUTES=10
    depends_on:
      weather-redis:
        condition: service_healthy
    restart: unless-stopped

  weather-redis:
    image: redis:7.2-alpine
    container_name: weather_redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 3s
      timeout: 3s
      retries: 5
    restart: unless-stopped

volumes:
  redis_data:
