name: Buf Generate

on:
  push:
    paths:
      - "proto/**"
      - "buf.yaml"
      - "buf.gen.yaml"
  pull_request:
    paths:
      - "proto/**"
      - "buf.yaml"
      - "buf.gen.yaml"

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23.x"

      - name: Install buf
        run: |
          curl -sSL https://github.com/bufbuild/buf/releases/latest/download/buf-Linux-x86_64 -o /usr/local/bin/buf
          chmod +x /usr/local/bin/buf

      - name: Generate Protobuf & ConnectRPC stubs
        run: buf generate

      - name: Check for changes
        run: |
          git config --global user.name "CI Bot"
          git config --global user.email "ci@example.com"
          if [[ -n $(git status --porcelain) ]]; then
            echo "Generated files changed. Please commit them."
            git diff
            exit 1
          else
            echo "No changes in generated files."
          fi
