name: Lint

on:
  push:         # Запускається на будь-який пуш
  pull_request: # Запускається на будь-який pull request

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23  

      - name: Install golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          skip-cache: true   # <-- вимикаємо кешування

      - name: Run golangci-lint
        run: golangci-lint run
